<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Laporan_model extends CI_Model
{

    public $table = 'tb_barang';
    public $id = 'id_barang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        return $this->db->select('id_barang, kode, nama, diskon, format(harga_beli,1) as harga_beli, format(harga_jual,1) as harga_jual, satuan')
        ->join('tb_satuan', 'id_satuan = satuan_id ')
        ->order_by($this->id, $this->order)
        ->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {   return $this->db->select('id_barang, kode, nama, diskon, format(harga_beli,1) as harga_beli, format(harga_jual,1) as harga_jual, satuan, satuan_id')
        ->join('tb_satuan', 'id_satuan = satuan_id ')
        ->where($this->id, $id)
        ->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_barang', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('diskon', $q);
	$this->db->or_like('harga_beli', $q);
	$this->db->or_like('harga_jual', $q);
	$this->db->or_like('satuan_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_barang', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('diskon', $q);
	$this->db->or_like('harga_beli', $q);
	$this->db->or_like('harga_jual', $q);
	$this->db->or_like('satuan_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Barang_model.php */
/* Location: ./application/models/Barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-21 00:24:54 */
/* http://harviacode.com */