<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pengguna_model extends CI_Model
{

    public $table = 'tb_user';
    public $id = 'id_user';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->load->model('dt_model');
    }

    // get all
    function get_all()
    {
        $table 		= $this->table;
        $select 	= 'tb_user.username, nama_lengkap, tb_user_level.level, id_user';
        $join[]		= [
            'table' => 'tb_user_level',
            'on' => 'tb_user.level = tb_user_level.id_level',
            'tipe' => 'inner',
        ];
        $where      = null;
        $like		= null;

        $column_search 	= ['username','nama_lengkap','tb_user_level.level'];
        $column_order 	= [null, $this->id];
        $order 			= [$this->id,$this->order]; 
        
        $list 		= $this->dt_model->dt_get($table, $select, $join, $where, $like, $column_search, $column_order, $order);
        
        $data_list 	= [];
        $no 		= $this->input->post('start');

        foreach ($list as $field) {

            $aksi = 
            anchor(site_url('master/pengguna/update/'.$field->id_user),'<i class="mdi mdi-tooltip-edit"></i>',array('title'=>'edit','class'=>'btn btn-info btn-sm'));
            $aksi .= ' ';
            $aksi .= anchor(site_url('master/pengguna/delete/'.$field->id_user),'<i class="mdi mdi-delete"></i>','title="delete" class="btn btn-info btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"');

            $no++;
            $row                = [];
            $row['no']          = $no;
            $row['username']          = $field->username;
            $row['nama_lengkap']         = $field->nama_lengkap;
            $row['level']    = $field->level;
            $row['act']         = $aksi;
            $data_list[] = $row;
        }

        $data = [
            "draw" 				=> $this->input->post("draw"),
            "recordsFiltered" 	=> $this->dt_model->dt_count_filtered($table, $this->id, $join, $where, $like, $column_search),
            "recordsTotal" 		=> $this->dt_model->dt_count_all($table, $this->id, $join, $where),
            "data" 				=> $data_list,
        ];

        return json_encode($data);
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file user_model.php */
/* Location: ./application/models/user_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-04 09:11:16 */
/* http://harviacode.com */