<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Satuan_model extends CI_Model
{

    public $table = 'tb_satuan';
    public $id = 'id_satuan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->load->model('dt_model');
    }

    // get all
    function get_all()
    {
        $table 		= $this->table;
        $select 	= '*';
        $join[]		= [
            'table'	=> "tb_barang b",
            'on'	=> "b.id_barang = tb_satuan.tb_barang_id",
            'tipe'	=> "inner",
        ];
        $where      = null;
        $like		= null;

        $column_search 	= ['id_barang','kode','nama','satuan'];
        $column_order 	= [null, $this->id];
        $order 			= [$this->id,$this->order]; 
        
        $list 		= $this->dt_model->dt_get($table, $select, $join, $where, $like, $column_search, $column_order, $order);
        
        $data_list 	= [];
        $no 		= $this->input->post('start');

        foreach ($list as $field) {

            $aksi = 
            anchor(site_url('master/satuan/update/'.$field->id_satuan),'<i class="mdi mdi-tooltip-edit"></i>',array('title'=>'edit','class'=>'btn btn-info btn-sm'));
            $aksi .= ' ';
            $aksi .= anchor(site_url('master/satuan/delete/'.$field->id_satuan),'<i class="mdi mdi-delete"></i>','title="delete" class="btn btn-info btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"');

            $no++;
            $row                = [];
            $row['no']          = $no;
            $row['barang']          = $field->nama;
            $row['satuan']         = $field->satuan;
            $row['rasio']    = $field->rasio;
            $row['act']         = $aksi;
            $data_list[] = $row;
        }

        $data = [
            "draw" 				=> $this->input->post("draw"),
            "recordsFiltered" 	=> $this->dt_model->dt_count_filtered($table, $this->id, $join, $where, $like, $column_search),
            "recordsTotal" 		=> $this->dt_model->dt_count_all($table, $this->id, $join, $where),
            "data" 				=> $data_list,
        ];

        return json_encode($data);
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_satuan', $q);
	$this->db->or_like('satuan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_satuan', $q);
	$this->db->or_like('satuan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Satuan_model.php */
/* Location: ./application/models/Satuan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-21 00:16:55 */
/* http://harviacode.com */